spring:
  config:
    import: "optional:configserver:"
  application:
    name: xchange

xchange:
  integration:
    lithuaniaBaseUrl: https://www.lb.lt
    lithuaniaBasePath: /webservices/FxRates/FxRates.asmx
    connectTimeoutMs: 5000
    readTimeoutMs: 20000
    writeTimeoutMs: 20000
    logLevel: INFO

server:
  port: 8080